// Data terpusat untuk semua konten website

export const siteConfig = {
  name: "Cake & Kue",
  description: "Toko kue online terbaik dengan cita rasa autentik",
  phone: "6281234567890", // Nomor WhatsApp tanpa +
  email: "info@cakeandkue.com",
  address: "Jl. Roti Manis No. 123, Jakarta",
  socialLinks: {
    instagram: "https://instagram.com/cakeandkue",
    facebook: "https://facebook.com/cakeandkue",
    tiktok: "https://tiktok.com/cakeandkue",
  },
};

export const navLinks = [
  { label: "Beranda", href: "/" },
  { label: "Produk", href: "/products" },
  { label: "Layanan", href: "/services" },
  { label: "Tentang", href: "/about" },
  { label: "Kontak", href: "/contact" },
];

export const products = [
  {
    id: 1,
    name: "Chocolate Cake Premium",
    price: 350000,
    category: "cake",
    rating: 4.8,
    reviews: 124,
    description: "Kue coklat berlapis dengan frosting premium dan topping coklat premium.",
    fullDescription: "Kue coklat premium dibuat dengan bahan-bahan pilihan terbaik. Dilengkapi dengan frosting coklat yang creamy dan topping coklat premium yang memberikan cita rasa istimewa. Cocok untuk acara spesial Anda.",
    image: "/chocolate-cake-premium-professional.jpg",
    images: [
      "/chocolate-cake-premium-professional.jpg",
      "/chocolate-cake-slice.png",
      "/chocolate-cake-decorated.jpg",
    ],
    serving: "8-10 orang",
    preparation: "2-3 hari sebelumnya",
    ingredients: "Tepung premium, coklat premium, butter, telur, gula, vanilla",
  },
  {
    id: 2,
    name: "Strawberry Shortcake",
    price: 320000,
    category: "cake",
    rating: 4.9,
    reviews: 156,
    description: "Kue sponge lembut berlapis krim dan stroberi segar.",
    fullDescription: "Shortcake klasik dengan sponge yang lembut dan ringan. Dipadukan dengan krim whipped fresh dan stroberi segar pilihan. Sangat sempurna untuk perayaan yang elegan.",
    image: "/strawberry-shortcake-fresh.jpg",
    images: [
      "/strawberry-shortcake-fresh.jpg",
      "/strawberry-shortcake-slice.jpg",
      "/strawberry-shortcake-decorated.jpg",
    ],
    serving: "6-8 orang",
    preparation: "1 hari sebelumnya",
    ingredients: "Tepung, telur, krim fresh, stroberi segar, gula, butter",
  },
  {
    id: 3,
    name: "Lemon Drizzle Cake",
    price: 280000,
    category: "cake",
    rating: 4.7,
    reviews: 89,
    description: "Kue lemon segar dengan glazir lemon yang tajam.",
    fullDescription: "Kue lemon yang segar dan ringan dengan glazir lemon yang memberikan sensasi asam-manis yang sempurna. Bahan-bahan premium dipilih untuk menghasilkan rasa yang autentik.",
    image: "/lemon-drizzle-cake-fresh.jpg",
    images: [
      "/lemon-drizzle-cake.jpg",
      "/lemon-cake-slice.jpg",
      "/lemon-cake-top-view.jpg",
    ],
    serving: "6-8 orang",
    preparation: "1-2 hari sebelumnya",
    ingredients: "Tepung, telur, lemon segar, gula, butter, glazir lemon",
  },
  {
    id: 4,
    name: "Tiramisu Layers",
    price: 300000,
    category: "cake",
    rating: 4.9,
    reviews: 203,
    description: "Tiramisu autentik dengan lapisan mascarpone yang creamy.",
    fullDescription: "Tiramisu klasik Italia dengan lapisan mascarpone yang creamy, kopi premium, dan cocoa powder. Rasanya yang autentik akan membawa Anda ke Italia.",
    image: "/tiramisu-layers-premium.jpg",
    images: [
      "/tiramisu-layers-premium.jpg",
      "/tiramisu-slice-detail.jpg",
      "/tiramisu-top-view.jpg",
    ],
    serving: "8-10 orang",
    preparation: "Minimal 5 jam di kulkas",
    ingredients: "Mascarpone, telur, gula, kopi premium, cocoa powder, biscuit",
  },
  {
    id: 5,
    name: "Red Velvet Cake",
    price: 330000,
    category: "cake",
    rating: 4.8,
    reviews: 145,
    description: "Kue red velvet elegan dengan krim cheese frosting.",
    fullDescription: "Red velvet cake yang elegan dengan warna merah yang memukau. Dipadukan dengan krim cheese frosting yang rich dan creamy. Sempurna untuk acara istimewa.",
    image: "/red-velvet-cake-elegant.jpg",
    images: [
      "/red-velvet-cake-elegant.jpg",
      "/red-velvet-slice.jpg",
      "/red-velvet-decorated.jpg",
    ],
    serving: "8-10 orang",
    preparation: "2-3 hari sebelumnya",
    ingredients: "Tepung, telur, butter, krim cheese, gula, vanillin, pewarna makanan",
  },
  {
    id: 6,
    name: "Blueberry Cheesecake",
    price: 340000,
    category: "cake",
    rating: 4.9,
    reviews: 178,
    description: "Cheesecake premium dengan lapisan blueberry segar.",
    fullDescription: "Cheesecake lembut dengan base biscuit, lapisan cheese yang creamy, dan topping blueberry segar. Kombinasi sempurna antara creamy dan fresh.",
    image: "/placeholder.svg?height=300&width=300",
    images: [
      "/placeholder.svg?height=500&width=500",
      "/placeholder.svg?height=500&width=500",
      "/placeholder.svg?height=500&width=500",
    ],
    serving: "8-10 orang",
    preparation: "Minimal 5 jam di kulkas",
    ingredients: "Cream cheese, butter, gula, telur, graham cracker, blueberry segar",
  },
];

export const pastries = [
  {
    id: 101,
    name: "Croissant Mentega",
    price: 35000,
    category: "pastry",
    rating: 4.7,
    reviews: 67,
    description: "Croissant renyah dengan lapisan mentega premium.",
    fullDescription: "Croissant autentik Perancis dengan lapisan mentega yang berlapis-lapis. Renyah di luar dan lembut di dalam. Sempurna untuk sarapan.",
    image: "/placeholder.svg?height=300&width=300",
    images: [
      "/placeholder.svg?height=500&width=500",
      "/placeholder.svg?height=500&width=500",
      "/placeholder.svg?height=500&width=500",
    ],
    serving: "1 pcs",
    preparation: "Siap ambil",
    ingredients: "Tepung premium, mentega premium, garam, gula, ragi",
  },
  {
    id: 102,
    name: "Donat Glazir",
    price: 28000,
    category: "pastry",
    rating: 4.8,
    reviews: 234,
    description: "Donat empuk dengan glazir gloss yang mengkilat.",
    fullDescription: "Donat empuk dan ringan dengan glazir gloss yang mengkilat. Tersedia berbagai varian rasa dan warna yang menarik.",
    image: "/placeholder.svg?height=300&width=300",
    images: [
      "/placeholder.svg?height=500&width=500",
      "/placeholder.svg?height=500&width=500",
      "/placeholder.svg?height=500&width=500",
    ],
    serving: "1 pcs",
    preparation: "Siap ambil",
    ingredients: "Tepung, telur, gula, vanilla, glazir premium",
  },
  {
    id: 103,
    name: "Tart Buah",
    price: 45000,
    category: "pastry",
    rating: 4.9,
    reviews: 156,
    description: "Tart dengan krim custard dan buah-buahan segar pilihan.",
    fullDescription: "Tart dengan base pastry yang renyah, krim custard yang creamy, dan buah-buahan segar pilihan. Setiap gigitan terasa premium.",
    image: "/placeholder.svg?height=300&width=300",
    images: [
      "/placeholder.svg?height=500&width=500",
      "/placeholder.svg?height=500&width=500",
      "/placeholder.svg?height=500&width=500",
    ],
    serving: "1 pcs",
    preparation: "Siap ambil",
    ingredients: "Pastry, krim custard, buah segar pilihan, glazir transparan",
  },
];

export const services = [
  {
    id: 1,
    title: "Custom Cake Design",
    description: "Desain kue custom sesuai tema dan keinginan Anda",
    icon: "🎨",
    fullDescription: "Kami menyediakan layanan desain kue custom dengan kreativitas tanpa batas. Tim kami siap mewujudkan konsep kue impian Anda untuk acara spesial.",
    features: [
      "Desain sesuai tema yang diinginkan",
      "Bahan premium pilihan",
      "Delivery tepat waktu",
      "Konsultasi desain gratis",
    ],
  },
  {
    id: 2,
    title: "Pesan untuk Acara",
    description: "Pesanan khusus untuk pernikahan, ulang tahun, dan acara lainnya",
    icon: "🎉",
    fullDescription: "Layanan pesan untuk acara spesial Anda. Kami menyediakan berbagai pilihan kue dan pastry untuk membuat acara Anda lebih berkesan.",
    features: [
      "Paket hemat untuk grup",
      "Dekorasi acara tersedia",
      "Staff profesional",
      "Sistem pembayaran fleksibel",
    ],
  },
  {
    id: 3,
    title: "Delivery & Setup",
    description: "Pengiriman cepat dan setup dekorasi profesional",
    icon: "🚚",
    fullDescription: "Kami menjamin pengiriman tepat waktu dengan packaging yang aman. Tim profesional kami siap melakukan setup dekorasi di lokasi acara Anda.",
    features: [
      "Pengiriman real-time tracking",
      "Packaging food grade",
      "Setup dekorasi profesional",
      "Garansi uang kembali",
    ],
  },
  {
    id: 4,
    title: "Kelas Baking",
    description: "Kelas baking untuk pemula hingga advanced",
    icon: "👨‍🍳",
    fullDescription: "Bergabunglah dengan kelas baking kami dan pelajari teknik membuat kue dari para ahli. Tersedia kelas individual atau group.",
    features: [
      "Instruktur berpengalaman",
      "Bahan premium disediakan",
      "Sertifikat setelah kelas",
      "Feedback personal",
    ],
  },
];

export const testimonials = [
  {
    id: 1,
    name: "Siti Nurhaliza",
    role: "Pengantin",
    content: "Kue pernikahan dari Cake & Kue sangat luar biasa! Rasa yang sempurna dan dekorasi yang indah. Semua tamu sangat terkesan!",
    avatar: "/placeholder.svg?height=80&width=80",
    rating: 5,
  },
  {
    id: 2,
    name: "Ahmad Rahman",
    role: "Pemilik Kafe",
    content: "Kerjasama dengan Cake & Kue sangat profesional. Produk berkualitas premium dan deliverynya selalu tepat waktu. Sangat merekomendasikan!",
    avatar: "/placeholder.svg?height=80&width=80",
    rating: 5,
  },
  {
    id: 3,
    name: "Budi Santoso",
    role: "Pelanggan Setia",
    content: "Sudah berkali-kali pesan di Cake & Kue dan selalu puas. Rasa yang konsisten dan selalu fresh. Lanjutkan!",
    avatar: "/placeholder.svg?height=80&width=80",
    rating: 5,
  },
  {
    id: 4,
    name: "Eka Putri",
    role: "Event Organizer",
    content: "Partner terpercaya kami untuk event klien. Cake & Kue selalu deliver quality dan profesionalisme. Sangat dihargai kolaborasinya!",
    avatar: "/placeholder.svg?height=80&width=80",
    rating: 5,
  },
];

export const faqItems = [
  {
    question: "Berapa lama proses pemesanan?",
    answer: "Proses pemesanan bisa dilakukan langsung via WhatsApp atau website. Kami akan konfirmasi dalam 30 menit. Pengerjaan tergantung kompleksitas desain, minimal 2 hari kerja.",
  },
  {
    question: "Apakah ada gratis ongkir?",
    answer: "Gratis ongkir untuk pembelian di atas Rp 500.000 dalam area Jakarta. Untuk area luar Jakarta, ongkir dihitung berdasarkan jarak dan berat produk.",
  },
  {
    question: "Bisa custom design?",
    answer: "Tentu! Kami sangat terbuka untuk custom design. Silakan sampaikan konsep Anda dan kami akan konsultasi untuk mewujudkannya. Ada biaya tambahan untuk desain kompleks.",
  },
  {
    question: "Bagaimana cara pembayaran?",
    answer: "Kami menerima transfer bank, e-wallet (GCash, GoPay, OVO), dan cash on delivery. Bayar sebagian dulu untuk booking, sisanya saat pengambilan/pengiriman.",
  },
];
